sales_table_ddl = '''
            CREATE TABLE IF NOT EXISTS {SALES_TABLE}(
                record_id varchar(255),
                report_id varchar(255),
                uuid varchar(255),
                created_at timestamp,
                file_name varchar(500),
                sheet_name varchar(255),
                number_of_records_in_sheet int,
                sender_email_address varchar(255),
                email_subject varchar(255),
                email_received_date varchar(50),
                reporting_period varchar(255),
                reporting_period_start varchar(255),
                reporting_period_end varchar(255),
                retailer_id varchar(50),
                retailer_name varchar(255),
                retailer_internal_id varchar(255),
                sell_through_channel varchar(255),
                store_id varchar(255),
                store_name varchar(255),
                region varchar(255),
                country varchar(255),
                state varchar(255),
                product_retailer_sku varchar(255),
                product_sku varchar(255),
                product_name varchar(255),
                product_size varchar(255),
                product_line varchar(255),
                currency varchar(255),
                total_quantity Decimal(20, 2),
                total_value Decimal(20, 2),
                return_quantity Decimal(20, 2),
                return_value Decimal(20, 2),
                free_replacements_quantity Decimal(20, 2),
                free_replacements_value Decimal(20, 2),
                tags varchar(255),
                type varchar(255),
                note varchar(255)
            );
'''