inventory_table_ddl = ''' 
            CREATE TABLE IF NOT EXISTS {INVENTORY_TABLE}(
                record_id varchar(255),
                report_id varchar(255),
                uuid varchar(255),
                created_at timestamp,
                file_name varchar(500),
                sheet_name varchar(255),
                number_of_records_in_sheet int,
                sender_email_address varchar(255),
                email_subject varchar(255),
                email_received_date varchar(50),
                effective_date varchar(255),
                retailer_id varchar(255),
                retailer_name varchar(255),
                retailer_internal_id varchar(255),
                plant_Id varchar(255),
                plant_name varchar(255),
                region varchar(255),
                country varchar(255),
                state varchar(255),
                product_retailer_sku varchar(255),
                product_sku varchar(255),
                product_name varchar(255),
                product_size varchar(255),
                product_line varchar(255),
                currency varchar(255),
                quantity_warehouse Decimal(20,2),
                quantity_physical Decimal(20,2),
                quantity_intransit Decimal(20,2),
                value_warehouse Decimal(20,2),
                value_physical Decimal(20,2),
                value_intransit Decimal(20,2),
                tags varchar(255),
                type varchar(255),
                note varchar(255)
            );
'''